# Generated by Django 4.1.3 on 2022-12-09 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(max_length=250)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('mobile', models.CharField(max_length=10, verbose_name='Téléphone')),
                ('status', models.BooleanField(default=True)),
                ('designation', models.CharField(max_length=50, null=True, verbose_name='désignation')),
                ('salary', models.CharField(max_length=50, null=True, verbose_name='salaire')),
                ('number_of_projects', models.IntegerField(null=True, verbose_name='nombre_de_projets')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='Nom')),
                ('phone', models.CharField(max_length=10, null=True, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, null=True, verbose_name='Email')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='titre')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(null=True, verbose_name='Date de création')),
                ('end_date', models.DateTimeField(null=True, verbose_name='Date de fin')),
                ('progress', models.IntegerField(null=True, verbose_name='progrès')),
                ('status', models.CharField(choices=[('en attente', 'en attente'), ('en traitement', 'en traitement'), ('fait', 'fait')], max_length=200, null=True, verbose_name='Status')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mainapp.customer')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True, verbose_name='titre')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.project')),
            ],
        ),
    ]
