# Generated by Django 4.1.3 on 2022-12-22 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='task',
            name='cost_per_houre',
            field=models.FloatField(null=True, verbose_name='coût par heure'),
        ),
        migrations.AddField(
            model_name='task',
            name='duration',
            field=models.IntegerField(null=True, verbose_name='durée'),
        ),
        migrations.AddField(
            model_name='task',
            name='total_cost',
            field=models.IntegerField(null=True, verbose_name='coût total'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Mainapp.customer', verbose_name='client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='profil'),
        ),
    ]
