# Generated by Django 4.1.3 on 2022-12-22 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_remove_project_created_date_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, null=True, verbose_name='Numéro de facture')),
                ('invoice_details', models.TextField(null=True, verbose_name='Détails de la facture')),
                ('project_duration', models.IntegerField(null=True, verbose_name='durée')),
                ('note', models.TextField(null=True, verbose_name='Remarque')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Mainapp.project')),
            ],
        ),
    ]
